
main: main.cpp
	g++ -o main main.cpp -I../../../libs/cailie -I../../../libs/gnulib/lib -L../../../build/libs/cailie -L../../../libs/gnulib/lib -L. -llibhelloworld -lcailie -lpthread -lgnu -lws2_32 -g

main_mpi: main.cpp
	mpic++ main.cpp -o main_mpi -I../../../libs/cailie -I../../../libs/gnulib/lib -L../../../build/libs/cailie -L../../../libs/gnulib/lib -L. -llibhelloworld_mpi -lcailiempi -lpthread -lgnu -lws2_32

clean:
	rm -f main main_mpi
